services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.20
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - published: 1883
        target: 1883
    volumes:
      - type: bind
        source: ./config/mosquitto.conf
        target: /mosquitto/conf/mosquitto.conf
        read_only: true
      - type: bind
        source: ./data
        target: /mosquitto/data
      - type: bind
        source: ./log
        target: /mosquitto/log
